package io.chrono.interchange.global.constant;

import java.util.Locale;

public enum Region {

    AFGHANISTAN(4, 30, "Asia/Kabul", Locale.forLanguageTag("af")),
    ALBANIA(1, 0, "Europe/Tirane", Locale.forLanguageTag("sq-AL")),
    ALGERIA(1, 0, "Africa/Algiers", Locale.forLanguageTag("ar-DZ")),
    ANDORRA(1, 0, "Europe/Andorra", Locale.forLanguageTag("ca-AD")),
    ANGOLA(1, 0, "Africa/Luanda", Locale.forLanguageTag("pt-AO")),
    ARGENTINA(-3, 0, "America/Argentina/Buenos_Aires", Locale.forLanguageTag("es-AR")),
    ARMENIA(4, 0, "Asia/Yerevan", Locale.forLanguageTag("hy-AM")),
    AUSTRALIA_SYDNEY(10, 0, "Australia/Sydney", Locale.forLanguageTag("en-AU")),
    AUSTRALIA_PERTH(8, 0, "Australia/Perth", Locale.forLanguageTag("en-AU")),
    AUSTRIA(1, 0, "Europe/Vienna", Locale.forLanguageTag("de-AT")),
    AZERBAIJAN(4, 0, "Asia/Baku", Locale.forLanguageTag("az-AZ")),
    BAHRAIN(3, 0, "Asia/Bahrain", Locale.forLanguageTag("ar-BH")),
    BANGLADESH(6, 0, "Asia/Dhaka", Locale.forLanguageTag("bn-BD")),
    BELARUS(3, 0, "Europe/Minsk", Locale.forLanguageTag("be-BY")),
    BELGIUM(1, 0, "Europe/Brussels", Locale.forLanguageTag("nl-BE")),
    BELIZE(-6, 0, "America/Belize", Locale.forLanguageTag("en-BZ")),
    BENIN(1, 0, "Africa/Porto-Novo", Locale.forLanguageTag("fr-BJ")),
    BHUTAN(6, 0, "Asia/Thimphu", Locale.forLanguageTag("dz-BT")),
    BOLIVIA(-4, 0, "America/La_Paz", Locale.forLanguageTag("es-BO")),
    BOSNIA_AND_HERZEGOVINA(1, 0, "Europe/Sarajevo", Locale.forLanguageTag("bs-BA")),
    BOTSWANA(2, 0, "Africa/Gaborone", Locale.forLanguageTag("en-BW")),
    BRAZIL(-3, 0, "America/Sao_Paulo", Locale.forLanguageTag("pt-BR")),
    BRUNEI(8, 0, "Asia/Brunei", Locale.forLanguageTag("ms-BN")),
    BULGARIA(2, 0, "Europe/Sofia", Locale.forLanguageTag("bg-BG")),
    BURKINA_FASO(0, 0, "Africa/Ouagadougou", Locale.forLanguageTag("fr-BF")),
    BURUNDI(2, 0, "Africa/Bujumbura", Locale.forLanguageTag("fr-BI")),
    CAMBODIA(7, 0, "Asia/Phnom_Penh", Locale.forLanguageTag("km-KH")),
    CAMEROON(1, 0, "Africa/Douala", Locale.forLanguageTag("fr-CM")),
    CANADA_EASTERN(-5, 0, "America/Toronto", Locale.CANADA),
    CANADA_CENTRAL(-6, 0, "America/Winnipeg", Locale.CANADA),
    CANADA_MOUNTAIN(-7, 0, "America/Denver", Locale.CANADA),
    CANADA_PACIFIC(-8, 0, "America/Vancouver", Locale.CANADA),
    CHAD(1, 0, "Africa/Ndjamena", Locale.forLanguageTag("fr-TD")),
    CHILE(-4, 0, "America/Santiago", Locale.forLanguageTag("es-CL")),
    CHINA(8, 0, "Asia/Shanghai", Locale.CHINA),
    COLOMBIA(-5, 0, "America/Bogota", Locale.forLanguageTag("es-CO")),
    COSTA_RICA(-6, 0, "America/Costa_Rica", Locale.forLanguageTag("es-CR")),
    CROATIA(1, 0, "Europe/Zagreb", Locale.forLanguageTag("hr-HR")),
    CUBA(-5, 0, "America/Havana", Locale.forLanguageTag("es-CU")),
    CYPRUS(2, 0, "Asia/Nicosia", Locale.forLanguageTag("el-CY")),
    CZECH_REPUBLIC(1, 0, "Europe/Prague", Locale.forLanguageTag("cs-CZ")),
    DENMARK(1, 0, "Europe/Copenhagen", Locale.forLanguageTag("da-DK")),
    DJIBOUTI(3, 0, "Africa/Djibouti", Locale.forLanguageTag("fr-DJ")),
    DOMINICAN_REPUBLIC(-4, 0, "America/Santo_Domingo", Locale.forLanguageTag("es-DO")),
    ECUADOR(-5, 0, "America/Guayaquil", Locale.forLanguageTag("es-EC")),
    EGYPT(2, 0, "Africa/Cairo", Locale.forLanguageTag("ar-EG")),
    EL_SALVADOR(-6, 0, "America/El_Salvador", Locale.forLanguageTag("es-SV")),
    ESTONIA(2, 0, "Europe/Tallinn", Locale.forLanguageTag("et-EE")),
    ETHIOPIA(3, 0, "Africa/Addis_Ababa", Locale.forLanguageTag("am-ET")),
    FIJI(12, 0, "Pacific/Fiji", Locale.forLanguageTag("fj-FJ")),
    FINLAND(2, 0, "Europe/Helsinki", Locale.forLanguageTag("fi-FI")),
    FRANCE(1, 0, "Europe/Paris", Locale.FRANCE),
    GABON(1, 0, "Africa/Libreville", Locale.forLanguageTag("fr-GA")),
    GAMBIA(0, 0, "Africa/Banjul", Locale.forLanguageTag("en-GM")),
    GEORGIA(4, 0, "Asia/Tbilisi", Locale.forLanguageTag("ka-GE")),
    GERMANY(1, 0, "Europe/Berlin", Locale.GERMANY),
    GHANA(0, 0, "Africa/Accra", Locale.forLanguageTag("en-GH")),
    GREECE(2, 0, "Europe/Athens", Locale.forLanguageTag("el-GR")),
    GREENLAND(-3, 0, "America/Godthab", Locale.forLanguageTag("kl-GL")),
    GUATEMALA(-6, 0, "America/Guatemala", Locale.forLanguageTag("es-GT")),
    GUINEA(0, 0, "Africa/Conakry", Locale.forLanguageTag("fr-GN")),
    GUINEA_BISSAU(0, 0, "Africa/Bissau", Locale.forLanguageTag("pt-GW")),
    GUYANA(-4, 0, "America/Guyana", Locale.forLanguageTag("en-GY")),
    HAITI(-5, 0, "America/Port-au-Prince", Locale.forLanguageTag("ht-HT")),
    HONDURAS(-6, 0, "America/Tegucigalpa", Locale.forLanguageTag("es-HN")),
    HONG_KONG(8, 0, "Asia/Hong_Kong", Locale.forLanguageTag("zh-HK")),
    HUNGARY(1, 0, "Europe/Budapest", Locale.forLanguageTag("hu-HU")),
    ICELAND(0, 0, "Atlantic/Reykjavik", Locale.forLanguageTag("is-IS")),
    INDIA(5, 30, "Asia/Kolkata", Locale.forLanguageTag("hi-IN")),
    INDONESIA_JAKARTA(7, 0, "Asia/Jakarta", Locale.forLanguageTag("id-ID")),
    INDONESIA_BALI(8, 0, "Asia/Makassar", Locale.forLanguageTag("id-ID")),
    IRAN(3, 30, "Asia/Tehran", Locale.forLanguageTag("fa-IR")),
    IRAQ(3, 0, "Asia/Baghdad", Locale.forLanguageTag("ar-IQ")),
    IRELAND(0, 0, "Europe/Dublin", Locale.forLanguageTag("en-IE")),
    ISRAEL(2, 0, "Asia/Jerusalem", Locale.forLanguageTag("he-IL")),
    ITALY(1, 0, "Europe/Rome", Locale.ITALY),
    IVORY_COAST(0, 0, "Africa/Abidjan", Locale.forLanguageTag("fr-CI")),
    JAMAICA(-5, 0, "America/Jamaica", Locale.forLanguageTag("en-JM")),
    JAPAN(9, 0, "Asia/Tokyo", Locale.JAPAN),
    JORDAN(2, 0, "Asia/Amman", Locale.forLanguageTag("ar-JO")),
    KAZAKHSTAN(6, 0, "Asia/Almaty", Locale.forLanguageTag("kk-KZ")),
    KENYA(3, 0, "Africa/Nairobi", Locale.forLanguageTag("sw-KE")),
    KIRIBATI(14, 0, "Pacific/Kiritimati", Locale.forLanguageTag("en-KI")),
    KUWAIT(3, 0, "Asia/Kuwait", Locale.forLanguageTag("ar-KW")),
    KYRGYZSTAN(6, 0, "Asia/Bishkek", Locale.forLanguageTag("ky-KG")),
    LAOS(7, 0, "Asia/Vientiane", Locale.forLanguageTag("lo-LA")),
    LATVIA(2, 0, "Europe/Riga", Locale.forLanguageTag("lv-LV")),
    LEBANON(2, 0, "Asia/Beirut", Locale.forLanguageTag("ar-LB")),
    LESOTHO(2, 0, "Africa/Maseru", Locale.forLanguageTag("en-LS")),
    LIBERIA(0, 0, "Africa/Monrovia", Locale.forLanguageTag("en-LR")),
    LIBYA(2, 0, "Africa/Tripoli", Locale.forLanguageTag("ar-LY")),
    LIECHTENSTEIN(1, 0, "Europe/Vaduz", Locale.forLanguageTag("de-LI")),
    LITHUANIA(2, 0, "Europe/Vilnius", Locale.forLanguageTag("lt-LT")),
    LUXEMBOURG(1, 0, "Europe/Luxembourg", Locale.forLanguageTag("lb-LU")),
    MACAU(8, 0, "Asia/Macau", Locale.forLanguageTag("zh-MO")),
    MADAGASCAR(3, 0, "Indian/Antananarivo", Locale.forLanguageTag("mg-MG")),
    MALAWI(2, 0, "Africa/Blantyre", Locale.forLanguageTag("en-MW")),
    MALAYSIA(8, 0, "Asia/Kuala_Lumpur", Locale.forLanguageTag("ms-MY")),
    MALDIVES(5, 0, "Indian/Maldives", Locale.forLanguageTag("dv-MV")),
    MALI(0, 0, "Africa/Bamako", Locale.forLanguageTag("fr-ML")),
    MALTA(1, 0, "Europe/Malta", Locale.forLanguageTag("mt-MT")),
    MARSHALL_ISLANDS(12, 0, "Pacific/Majuro", Locale.forLanguageTag("mh-MH")),
    MAURITANIA(0, 0, "Africa/Nouakchott", Locale.forLanguageTag("ar-MR")),
    MAURITIUS(4, 0, "Indian/Mauritius", Locale.forLanguageTag("mfe-MU")),
    MEXICO_CITY(-6, 0, "America/Mexico_City", Locale.forLanguageTag("es-MX")),
    MICRONESIA(11, 0, "Pacific/Pohnpei", Locale.forLanguageTag("en-FM")),
    MOLDOVA(2, 0, "Europe/Chisinau", Locale.forLanguageTag("ro-MD")),
    MONACO(1, 0, "Europe/Monaco", Locale.forLanguageTag("fr-MC")),
    MONGOLIA(8, 0, "Asia/Ulaanbaatar", Locale.forLanguageTag("mn-MN")),
    MONTENEGRO(1, 0, "Europe/Podgorica", Locale.forLanguageTag("sr-ME")),
    MOROCCO(1, 0, "Africa/Casablanca", Locale.forLanguageTag("ar-MA")),
    MOZAMBIQUE(2, 0, "Africa/Maputo", Locale.forLanguageTag("pt-MZ")),
    MYANMAR(6, 30, "Asia/Yangon", Locale.forLanguageTag("my-MM")),
    NAMIBIA(2, 0, "Africa/Windhoek", Locale.forLanguageTag("en-NA")),
    NAURU(12, 0, "Pacific/Nauru", Locale.forLanguageTag("en-NR")),
    NEPAL(5, 45, "Asia/Kathmandu", Locale.forLanguageTag("ne-NP")),
    NETHERLANDS(1, 0, "Europe/Amsterdam", Locale.forLanguageTag("nl-NL")),
    NEW_ZEALAND(12, 0, "Pacific/Auckland", Locale.forLanguageTag("en-NZ")),
    NICARAGUA(-6, 0, "America/Managua", Locale.forLanguageTag("es-NI")),
    NIGER(1, 0, "Africa/Niamey", Locale.forLanguageTag("fr-NE")),
    NIGERIA(1, 0, "Africa/Lagos", Locale.forLanguageTag("en-NG")),
    NORTH_KOREA(9, 0, "Asia/Pyongyang", Locale.forLanguageTag("ko-KP")),
    NORWAY(1, 0, "Europe/Oslo", Locale.forLanguageTag("nb-NO")),
    OMAN(4, 0, "Asia/Muscat", Locale.forLanguageTag("ar-OM")),
    PAKISTAN(5, 0, "Asia/Karachi", Locale.forLanguageTag("ur-PK")),
    PALAU(9, 0, "Pacific/Palau", Locale.forLanguageTag("pau-PW")),
    PALESTINE(2, 0, "Asia/Gaza", Locale.forLanguageTag("ar-PS")),
    PANAMA(-5, 0, "America/Panama", Locale.forLanguageTag("es-PA")),
    PAPUA_NEW_GUINEA(10, 0, "Pacific/Port_Moresby", Locale.forLanguageTag("tpi-PG")),
    PARAGUAY(-4, 0, "America/Asuncion", Locale.forLanguageTag("gn-PY")),
    PERU(-5, 0, "America/Lima", Locale.forLanguageTag("es-PE")),
    PHILIPPINES(8, 0, "Asia/Manila", Locale.forLanguageTag("fil-PH")),
    POLAND(1, 0, "Europe/Warsaw", Locale.forLanguageTag("pl-PL")),
    PORTUGAL(0, 0, "Europe/Lisbon", Locale.forLanguageTag("pt-PT")),
    QATAR(3, 0, "Asia/Qatar", Locale.forLanguageTag("ar-QA")),
    REPUBLIC_OF_KOREA(9, 0, "Asia/Seoul", Locale.KOREA),
    ROMANIA(2, 0, "Europe/Bucharest", Locale.forLanguageTag("ro-RO")),
    RUSSIA_MOSCOW(3, 0, "Europe/Moscow", Locale.forLanguageTag("ru-RU")),
    RWANDA(2, 0, "Africa/Kigali", Locale.forLanguageTag("rw-RW")),
    SAINT_KITTS_AND_NEVIS(-4, 0, "America/St_Kitts", Locale.forLanguageTag("en-KN")),
    SAINT_LUCIA(-4, 0, "America/St_Lucia", Locale.forLanguageTag("en-LC")),
    SAINT_VINCENT_AND_THE_GRENADINES(-4, 0, "America/St_Vincent", Locale.forLanguageTag("en-VC")),
    SAMOA(13, 0, "Pacific/Apia", Locale.forLanguageTag("sm-WS")),
    SAN_MARINO(1, 0, "Europe/San_Marino", Locale.forLanguageTag("it-SM")),
    SAO_TOME_AND_PRINCIPE(0, 0, "Africa/Sao_Tome", Locale.forLanguageTag("pt-ST")),
    SAUDI_ARABIA(3, 0, "Asia/Riyadh", Locale.forLanguageTag("ar-SA")),
    SENEGAL(0, 0, "Africa/Dakar", Locale.forLanguageTag("fr-SN")),
    SERBIA(1, 0, "Europe/Belgrade", Locale.forLanguageTag("sr-RS")),
    SEYCHELLES(4, 0, "Indian/Mahe", Locale.forLanguageTag("fr-SC")),
    SIERRA_LEONE(0, 0, "Africa/Freetown", Locale.forLanguageTag("en-SL")),
    SINGAPORE(8, 0, "Asia/Singapore", Locale.forLanguageTag("en-SG")),
    SLOVAKIA(1, 0, "Europe/Bratislava", Locale.forLanguageTag("sk-SK")),
    SLOVENIA(1, 0, "Europe/Ljubljana", Locale.forLanguageTag("sl-SI")),
    SOLOMON_ISLANDS(11, 0, "Pacific/Guadalcanal", Locale.forLanguageTag("en-SB")),
    SOMALIA(3, 0, "Africa/Mogadishu", Locale.forLanguageTag("so-SO")),
    SOUTH_AFRICA(2, 0, "Africa/Johannesburg", Locale.forLanguageTag("af-ZA")),
    SOUTH_SUDAN(3, 0, "Africa/Juba", Locale.forLanguageTag("en-SS")),
    SPAIN(1, 0, "Europe/Madrid", Locale.forLanguageTag("es-ES")),
    SRI_LANKA(5, 30, "Asia/Colombo", Locale.forLanguageTag("si-LK")),
    SUDAN(2, 0, "Africa/Khartoum", Locale.forLanguageTag("ar-SD")),
    SURINAME(-3, 0, "America/Paramaribo", Locale.forLanguageTag("nl-SR")),
    SWAZILAND(2, 0, "Africa/Mbabane", Locale.forLanguageTag("en-SZ")),
    SWEDEN(1, 0, "Europe/Stockholm", Locale.forLanguageTag("sv-SE")),
    SWITZERLAND(1, 0, "Europe/Zurich", Locale.forLanguageTag("de-CH")),
    SYRIA(2, 0, "Asia/Damascus", Locale.forLanguageTag("ar-SY")),
    TAIWAN(8, 0, "Asia/Taipei", Locale.forLanguageTag("zh-TW")),
    TAJIKISTAN(5, 0, "Asia/Dushanbe", Locale.forLanguageTag("tg-TJ")),
    TANZANIA(3, 0, "Africa/Dar_es_Salaam", Locale.forLanguageTag("sw-TZ")),
    THAILAND(7, 0, "Asia/Bangkok", Locale.forLanguageTag("th-TH")),
    TIMOR_LESTE(9, 0, "Asia/Dili", Locale.forLanguageTag("pt-TL")),
    TOGO(0, 0, "Africa/Lome", Locale.forLanguageTag("fr-TG")),
    TONGA(13, 0, "Pacific/Tongatapu", Locale.forLanguageTag("to-TO")),
    TRINIDAD_AND_TOBAGO(-4, 0, "America/Port_of_Spain", Locale.forLanguageTag("en-TT")),
    TUNISIA(1, 0, "Africa/Tunis", Locale.forLanguageTag("ar-TN")),
    TURKEY(3, 0, "Europe/Istanbul", Locale.forLanguageTag("tr-TR")),
    TURKMENISTAN(5, 0, "Asia/Ashgabat", Locale.forLanguageTag("tk-TM")),
    TUVALU(12, 0, "Pacific/Funafuti", Locale.forLanguageTag("en-TV")),
    UGANDA(3, 0, "Africa/Kampala", Locale.forLanguageTag("sw-UG")),
    UKRAINE(2, 0, "Europe/Kiev", Locale.forLanguageTag("uk-UA")),
    UNITED_ARAB_EMIRATES(4, 0, "Asia/Dubai", Locale.forLanguageTag("ar-AE")),
    UNITED_KINGDOM(0, 0, "Europe/London", Locale.UK),
    UNITED_STATES_EASTERN(-5, 0, "America/New_York", Locale.US),
    UNITED_STATES_CENTRAL(-6, 0, "America/Chicago", Locale.US),
    UNITED_STATES_MOUNTAIN(-7, 0, "America/Denver", Locale.US),
    UNITED_STATES_PACIFIC(-8, 0, "America/Los_Angeles", Locale.US),
    URUGUAY(-3, 0, "America/Montevideo", Locale.forLanguageTag("es-UY")),
    UZBEKISTAN(5, 0, "Asia/Tashkent", Locale.forLanguageTag("uz-UZ")),
    VANUATU(11, 0, "Pacific/Efate", Locale.forLanguageTag("bi-VU")),
    VATICAN(1, 0, "Europe/Vatican", Locale.ITALY),
    VENEZUELA(-4, 0, "America/Caracas", Locale.forLanguageTag("es-VE")),
    VIETNAM(7, 0, "Asia/Ho_Chi_Minh", Locale.forLanguageTag("vi-VN")),
    YEMEN(3, 0, "Asia/Aden", Locale.forLanguageTag("ar-YE")),
    ZAMBIA(2, 0, "Africa/Lusaka", Locale.forLanguageTag("en-ZM")),
    ZIMBABWE(2, 0, "Africa/Harare", Locale.forLanguageTag("en-ZW"));

    private final int utcOffsetHours;
    private final int utcOffsetMinutes;
    private final String timeZone;
    private final Locale locale;

    Region(int utcOffsetHours, int utcOffsetMinutes, String timeZone, Locale locale) {
        this.utcOffsetHours = utcOffsetHours;
        this.utcOffsetMinutes = utcOffsetMinutes;
        this.timeZone = timeZone;
        this.locale = locale;
    }

    public int getUtcOffsetHours() {
        return utcOffsetHours;
    }

    public int getUtcOffsetMinutes() {
        return utcOffsetMinutes;
    }

    public String getTimeZone() {
        return timeZone;
    }

    public Locale getLocale() {
        return locale;
    }
}
